name: Clang_Format_Check

on:
  push:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/clang_format_check.yml
      - include/**
      - test/unit_test/**
      - .clang-format
      - tool/clang_format/**
  pull_request:
    paths:
      - .github/workflows/clang_format_check.yml
      - include/**
      - test/unit_test/**
      - .clang-format
      - tool/clang_format/**
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref || github.run_id}}
  cancel-in-progress: true

jobs:
  format-check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - include/fkYAML
          - test/unit_test

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '14'
        check-path: ${{matrix.path}}
