name: Coverage

on:
  push:
    branches:
      # Run coverage workflows on all the commits pushed to the following branches
      # following the recommended CI configurations for Coveralls.
      # https://docs.coveralls.io/build-types#recommended-ci-configurations
      - develop
      - main
  # Run on pull requests from both branches and forks.
  pull_request:
    paths:
      - .github/workflows/coverage.yml
      - cmake/**
      - include/**
      - tests/**
      - CMakeLists.txt
      - Makefile
  workflow_dispatch:

jobs:
  coverage:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7
      with:
        repository: ${{github.event.pull_request.head.repo.full_name || github.repository}}
        ref: ${{github.event.pull_request.head.sha || github.sha}}
        persist-credentials: false

    - name: Install lcov
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov
        lcov --version

    - name: Generate coverage
      run: make html-coverage

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        file: ${{github.workspace}}/build_coverage/coverage/fkYAML.info
        format: lcov

    - name: Decide the artifact name
      id: create_zip
      env:
        PR_NUMBER: ${{github.event.number}}
      run: |
        echo "artifact name: fkYAML_coverage.pr${{env.PR_NUMBER}}"
        echo "artifact_name=fkYAML_coverage.pr${{env.PR_NUMBER}}" >> $GITHUB_OUTPUT

    - name: Upload coverage as an artifact
      id: upload_artifact_step
      if: steps.create_zip.conclusion == 'success'
      uses: actions/upload-artifact@v7
      with:
        name: ${{steps.create_zip.outputs.artifact_name}}
        path: |
          ${{github.workspace}}/build_coverage/coverage/*
          ${{github.workspace}}/build_coverage/html/**
        overwrite: true

